version: '3.4'

services:
  accountingsoftware:
    image: accountingsoftware
    build:
      context: AccountingSoftware
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 8000:8000
